version: 2
enable-beta-ecosystems: true
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/video_duration_native"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/video_duration_native/example"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/video_duration_native_platform_interface"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/video_duration_native_android"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/video_duration_native_ios"
    schedule:
      interval: "daily"